### ISSUE TITLE
图片加载不出来。。。给的是URL

### ISSUE THREAD

**Issue by mistak1992** [stackhou/YJBannerView#10]
本地的图片就可以，网络的图片就会失败

**Comment by mistak1992** [comment]
懂了，必须要自定义cell才能显示，醉醉的

**Comment by stackhou** [comment]
这和自定义cell没关系，看demo里面有网络图片的显示

**Comment by mistak1992** [comment]
是的，我实现了数据源方法，打断点确实也走了，不行，页面空白，有页面指示器
然后把数据源换成Demo中的图片地址，不行，页面空白，有页面指示器
最后我实现了额外实现了自定义cell的三个方法，并且自定义了cell(用SD_web下载图片填充)，可以了
