### ISSUE TITLE
未注册cell 闪退

### ISSUE THREAD

**Issue by YiHuaXie** [stackhou/YJBannerView#11]
could not dequeue a view of kind: UICollectionElementKindCell with identifier MessageCell - must register a nib or a class for the identifier or connect a prototype cell in a storyboard    我已经实现了bannerViewRegistCustomCellClass 和 reuseIdentifierForIndex方法  不知道为什么还是会闪退

**Comment by stackhou** [comment]
仔细看下demo吧，应该是没有注册成功，看看具体原因吧

**Comment by xieyihua** [comment]
不知道为什么   因为不是必现的crash

**Comment by stackhou** [comment]
嗯，再试试，看看bug呈现步骤是什么
