### ISSUE TITLE
crash on iOS 8.1

### ISSUE THREAD

**Issue by xieyihua** [stackhou/YJBannerView#12]
在iOS 8.1的时候  设置bannerGestureEnable = NO,会出现野指针`[UIScrollViewPagingSwipeGestureRecognizer setEnabled:]: message sent to deallocated instance 0x7fe951662280
(lldb) `
我看了下代码  ：
` for (UIGestureRecognizer *gesture in self.collectionView.gestureRecognizers) {
            [self.collectionView removeGestureRecognizer:gesture];
        }`
我想你可能只是想删除掉Pan的手势，是不是应该加一个`if ([gesture isKindOfClass:[UIPanGestureRecognizer class]])`？？

**Comment by stackhou** [comment]
tnk，2.4.0中已经修复了这个问题
