### ISSUE TITLE
demo事例中BannerView在手机息屏后，解锁后Banner直接卡住

### ISSUE THREAD

**Issue by FelixYin66** [stackhou/YJBannerView#14]
运行demo后，在手机息屏后再打开手机，Banner直接卡住。当进入后台，再次进来就可以恢复。这个是运行循环的事

**Comment by stackhou** [comment]
这个是我用Demo测试后台任务时间造成的，和YJBannerView组件没有关系，感谢您细心发现

**Comment by FelixYin66** [comment]
okay，我已经发现问题所在了...
- (void)applicationDidEnterBackground:(UIApplication *)application {
    // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
    // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
    
    [[YJBackgroundTask sharedInstance] beginBackgroundTaskWithLastTime:5 completion:^{
        NSLog(@"-->%@", @"7之前是10分钟，7之后是3分钟，后台结束了");
    }];
}


这句代码在应用进入后台后会被执行，里面有一个死循环.....😄😄😄😄

**Comment by stackhou** [comment]
嗯，是的，这个和这个组件没有关系，放心使用
