### ISSUE TITLE
你好 把bannerView放在tableview tableHeaderView上拖拽不了  

### ISSUE THREAD

**Issue by pocketChao** [stackhou/YJBannerView#6]
_bannerView = [YJBannerView bannerViewWithFrame:CGRectMake(0, 0, SCREEN_WIDTH, SCREEN_WIDTH) dataSource:self delegate:self emptyImage:[UIImage imageNamed:@""] placeholderImage:[UIImage imageNamed:@"placeHolder"] selectorString:@"sd_setImageWithURL:placeholderImage:"];
        _bannerView.bannerGestureEnable = YES;
        _bannerView.pageControlStyle = PageControlNone;
        _bannerView.autoDuration = 2.5f;

**Comment by stackhou** [comment]
不能够，你看看demo里面就有例子 bannerGestureEnable 默认就是YES

**Comment by pocketChao** [comment]
啊 是啊  我这个是tableview 嵌套 你的bannerView 手势应该有冲突🤦‍♀️ 我再研究研究 哈哈 谢谢
