### ISSUE TITLE
希望可以多的开放一些接口 来实现自定义Cell

### ISSUE THREAD

**Issue by TonyGJJ** [stackhou/YJBannerView#7]
希望可以多的开放一些接口 来实现自定义Cell

**Comment by stackhou** [comment]
完全支持自定义cell，并且还支持指定多种不同类型的cell, 源码里面有Demo，您需要开放什么接口？

**Comment by TonyGJJ** [comment]
这个地方的 图片我想要控制大小 

因为我们现在App的设计 有两种 样式  一种是 图片 宽度是 屏幕的宽度 另外一种样式是 左、右预留了一定的间隙。  但是  UICollectionView 都需要为屏幕宽度 也就是 说  图片消失和展示的其实点都是屏幕的最外侧， 不知道 这样说 能不能理解

第一种样式

  第二种样式

**Comment by TonyGJJ** [comment]
嗯 看到了。已经找到方法了  打扰了

**Comment by stackhou** [comment]
嗯，有什么需求无法实现的，提出来我会更新它

**Comment by TonyGJJ** [comment]
嗯，好的。 只是 自定义 Cell 那块调用比较繁琐。。。完整看完一遍Demo 才发现有这样的方法。。。

**Comment by TonyGJJ** [comment]
你好，可以添加一个 新的  pageControlDotSize 方法吗？比如 当前 size  和 为选中的size

**Comment by TonyGJJ** [comment]
你好，可以添加一个 新的  pageControlDotSize 方法吗？比如 当前 size  和 为选中的size
