### ISSUE TITLE
支持播放视频和无限轮播吗？

### ISSUE THREAD

**Issue by JIANHUI2015** [stackhou/YJBannerView#8]
如题，Demo中是像淘宝商品一样，不支持无限轮播。

**Comment by stackhou** [comment]
可以开启无限轮播和自动轮播的，看相关API
![001](https://user-images.githubusercontent.com/473027/39915422-7ee05a0e-553a-11e8-9a95-9f390c118d56.png)

**Comment by JIANHUI2015** [comment]
我试过了，会奔溃。
因为Demo中indexPath中的section写死了是0。
但是无限轮播的话section并不是0

**Comment by JIANHUI2015** [comment]
非常感谢~

**Comment by stackhou** [comment]
看我最新的提交里面有Demo，已经包含无限循环带视频。
