### ISSUE TITLE
pod install 时 source路径与实际不一样

### ISSUE THREAD

**Issue by MQL9011** [stackhou/YJBannerView#9]
pod install 时找的 source 是 "https://github.com/stackhou/YJBannerViewOC.git"

而实际代码仓库地址是"https://github.com/stackhou/YJBannerView.git"

貌似导致pod install时失败

**Comment by MQL9011** [comment]
podspec 中的s.source建议改下

**Comment by stackhou** [comment]
2.3.9 中source已经修正，谢谢提醒
